### PR TITLE
Feat/handle test case multiple types

### PR DESCRIPTION
**Pull request by jeswr**
Supercedes #88 

 - Creates multiple test cases when there are multiple handlers to support it
 - Adds query and parsing e2e tests to catch the original problem in #88 where the jsonld test suite was broken and we almost didn't notice
 - Exports `content-type` mappings for consumers to use
 - Removes the node 14 CI check since this conflicts with the lru-cache package (transitive dep of the comunica dev. dependencies) requiring node 16+. I figured this isn't too much of a problem since Node 14s LTS finishes at the end of April.

### CODE REVIEW

**Comment by rubensworks** [comment]
Really like the e2e tests, this will significantly simplify testing! :-)

> Removes the node 14 CI check since this conflicts with the lru-cache package

Not sure I understand why this is needed. Comunica's CI also still runs on Node 14, so its transitive deps should still work fine there. I would prefer not dropping Node 14 support until absolutely necessary.

**Comment by rubensworks** [comment]
But Comunica doesn't use that version yet. This is why we haven't merged this PR yet: https://github.com/comunica/comunica/pull/1172

**Comment by rubensworks** [comment]
Huh, interesting. Something must be going wrong with version resolution somewhere then.

**Comment by jeswr** [comment]
I've manually patched the lockfile for now to get it to resolve to a v7 but long term we need to remove your dependence on the types package.

**Comment by jeswr** [comment]
@rubensworks - the tests are passing but a bit flakey because of https://github.com/rubensworks/rdf-test-suite.js/issues/64. 

I'd suggest we use https://www.npmjs.com/package/fetch-retry with exponential backoff if problems continue.

**Comment by rubensworks** [comment]
Released as 1.23.0

**Pull request merged**
